trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo Cloning repo to local directory
    git clone https://github.com/Nilesh1721/Test-Guess-No
  displayName: 'Clone Repo'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Linux Testing'  # Adjusted to existing service name
    sourceFolder: '$(Build.SourcesDirectory)/Test-Guess-No'
    contents: '**'
    targetFolder: '/home/nilesh/file'
    cleanTargetFolder: true

- task: SSH@0
  inputs:
    sshEndpoint: 'Linux Testing'
    runOptions: 'commands'
    command: |
      cd /home/nilesh/file
      pip3 install flask
      nohup python3 app.py &
